version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: acta_postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - acta_network

volumes:
  postgres_data:

networks:
  acta_network:
    driver: bridge 